package com.apacy.queryoptimizer.parser;

public enum TokenType {
    // keywords
    SELECT, FROM, WHERE, INSERT, UPDATE, DELETE, INTO, VALUES, SET,
    JOIN, ON, NATURAL, CROSS, INNER, OUTER, LEFT, RIGHT, FULL, ORDER, BY, DESC, ASC, LIMIT, OFFSET, CREATE, TABLE, DROP, AS,
    INDEX, USING, BTREE, HASH,
    FOREIGN, PRIMARY, KEY, CASCADE, RESTRICT, REFERENCES,
    BEGIN, TRANSACTION, COMMIT, ABORT,
    AND, OR, NOT,
    FALSE, TRUE,

    // symbols
    OPERATOR, LPARENTHESIS, RPARENTHESIS,
    COMMA, SEMICOLON, STAR, DOT,

    // Literals
    IDENTIFIER, STRING_LITERAL, NUMBER_LITERAL,

    // End of input
    EOF
}